### ISSUE TITLE
Jira projects with 4 characters not pushing time logs.

### ISSUE THREAD

**Issue by Archimedyz** [Daniel-Aragao/TogglToJira#2]
# Description
I have tickets under a project with code INTG. So If I log time to "INTG-123", it's picking this up as just "NTG-123", effectively trimming off the leading `I`. It does this for the preview, and also when publishing. As a result, I can't use the tool to publish logs for INTG tickets; I am doing them manually.

# Example
Here's what I have in my Toggl app:
<img width="633" alt="image" src="https://github.com/Daniel-Aragao/TogglToJira/assets/1493104/109ad2e9-043a-419d-ac27-d8e3a71e5e61">

Here's what I see in the CLI when using the tool. (Note: `tog` is an alias to the TogglToJira tool):
<img width="770" alt="image" src="https://github.com/Daniel-Aragao/TogglToJira/assets/1493104/10a3c40e-101f-42e7-b3a8-48bfaf03c917">

# Reproduction Steps
1. Open Toggl, and add a new time entry.
2. For the description use put a Jira ticket with a four letter code (e.g. "INTG-123")
3. Make sure the time entry is over 1 minute long.
4. Use the TogglToJira tool to generate the report/preview.
    - **<span style="color:red">The output will show the time entry, for ticket "NTG-123".</span>**
5. Now use the ToggleToJira tool to send the logs, via the `-p` option.
    - **<span style="color:red">The output will send other logs, but will fail to send the log created in steps 1-3 since the ticket "NTG-123" doesn't exist.</span>**

**Comment by Daniel-Aragao** [comment]
Hi,

this bug was previously attended and shouldn't happen with the latest version, may I ask you to update and confirm if it still failing?

**Comment by Archimedyz** [comment]
I updated to the latest version, and can confirm that the preview shows the ticket properly.

However, I did accidentally clear my credentials during the update, and while going through the readme, I noticed it needs to be updated:
![image](https://github.com/Daniel-Aragao/TogglToJira/assets/1493104/4012853a-b034-4aee-b404-487d157a979e)
